{% set name = "jsonpickle" %}
{% set version = "4.1.1" %}
{% set sha256 = "f86e18f13e2b96c1c1eede0b7b90095bbb61d99fedc14813c44dc2f361dbbae1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # noarch: python
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - wheel
    - python
    - setuptools >=42
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python
    - importlib_metadata  # [py<38]

test:
  requires:
    - pip
  imports:
    - jsonpickle
  commands:
    - pip check

about:
  home: https://jsonpickle.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for serializing any arbitrary object graph into JSON
  description: |
    jsonpickle is a library for the two-way conversion of complex Python
    objects and JSON. jsonpickle builds upon the existing JSON encoders,
    such as simplejson, json, and ujson.
  dev_url: https://github.com/jsonpickle/jsonpickle
  doc_url: https://github.com/jsonpickle/jsonpickle/blob/main/README.rst

extra:
  recipe-maintainers:
    - robmcmullen
    - ChrisBarker-NOAA
    - synapticarbors
