{% set name = "jsonpickle" %}
{% set version = "1.3" %}
{% set sha256 = "71bca2b80ae28af4e3f86629ef247100af7f97032b5ca8d791c1f8725b411d95" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - jsonpickle

about:
  summary: Python library for serializing any arbitrary object graph into JSON. It can take almost any Python object and turn the object into JSON. Additionally, it can reconstitute the object back into Python.
  home: http://jsonpickle.github.io/
  dev_url: https://github.com/jsonpickle/jsonpickle
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING

extra:
  recipe-maintainers:
    - robmcmullen
    - ChrisBarker-NOAA
