travis:
  secure:
    BINSTAR_TOKEN: QiUH6ARmhyPYOWFJlXzuFc3LTh9fnMA0hKWDHT+2ee139qdXXmZveUq5N/sXuXZXGBhF0y4ZwL2ao0t4LnKYOr7w1F9fq7ZpJiRekfXdaTC77sLUNSz1CptMy8DAAYJznNKTEK53jCDIjN0imllvhYCWszyZo5GWbF8fMhf/fZxnvYPL2tQUM4Ac8N/4I5kE+WrOfi2lOxMGEVCGuyduUplz+aJn6qGeyXOsvTz3SadlcdwMBxDXslbFY9UmPgUUILgw+JCVo+46XssAZRFyoVyI3b34XxrCa7sWQrxtdt0oR4jHqMzVvf0HhWtAdqG47jp9bV2ZQqZJ4ZvHSzDz6uywLxvykGGdzAuutLhG5dXNPH+JSYfjJ9rX+jnIlcygtWslGKIjSssmmmXaQuTduMA7tIsRYnWfKy7Gt1p9B4dZDiMdbuB4BPTFMAyRuh983qpw0fDBCOj/9B1Rf39dUBRyg4F32iJcTZU3mD0JM3fGx9jW8O6ppKhJNfSjnRRUyBEsDxkqSp3mb7cRnRMaPdh21JhfsSzcBlSIbPmp7Jd3UPO6wH9WFMK9osRF3HPR/1ewSFI3K+yIjStf63j8eNmmEgvbafMljrQ6QP/paHl0DJKOGH+nLB1wW4xHI2OjdpP5r7NRfvrU0LOJ45KgWKyDVk9dZJpSjWArenRKgHM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
