travis:
  secure:
    BINSTAR_TOKEN: oSQUcWNA8ok1/sjk2pE8UhMohD9gLKB1j9CKAcoOlHHNBl+w4QPrK5Pj8cLF3f/5biWiT/Vs+bpjB+EBWckhvUbC7/LiOKtooWUypv5Wm0M4Ocs8Qhg0bl2auJ512dXwDdeSLDMuwN2Nq3ZkIMhba4oSIAgl/w4hIhFnVAkZ6JLAEMvE1bEjMrzrTKgTut285q1KEKquy2ezOuyMHFkVACqyq8QANcD7h7JeGM+rmWSqJM+OuhNxk1PA1sV/tDL9TUJCWtGgk6j/fMvHs+bJjGIKw1vz3apD77Pkh1DnFLkEPkk1DQdsRep956wCmDm2UZ31hvu3PCrXaiB035YksBY1YUUHzCcwbNi1XSj6g3eX7pzq1Bi8lrAziHkwecoHI/wCBUfxCkeOJjXdkD5peM2fwPRLjyHgjUKOmeea2paip7JEuyj8opv34e9YTWaJ++t7PCvrC/Uj1E/U85tIuJ+u3tqrAFxUtXzIWHhSfsQ3G5aR9A7esedJaetHutDz27z8AwFE1N6+mm/kApjUug8DKszXTJCM3mpBUxRm0l8vq210KsrLIWmU89DDxwkTNXYZ46sNbO4xAoP1rbH32IeenE6TN6zkE20untkuFyDGdIBZqGjUZHG20rFxm1PreqlBD07DXfmq2edaMPxF0J6N4TdrWGJ/QYpQvirGOOE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
